### ISSUE TITLE
萌新执行不了？

### ISSUE THREAD

**Issue by winghuer520** [CharesFang/Sina-Weibo-Spider#2]
cannot import name 'log' from 'scrapy'

**Comment by 112798** [comment]
可能是版本的问题，Scrapy版本1.5之后就弃用了log，不过我还觉得log挺好用的，用anaconda换15或者1.6版本的Scrapy都没问题，过几天会发一个数据库结构文档上来，没有数据库的话piplines会报错，当然可以直接禁用pipelines或者重写pipelines都么问题；这爬虫我也还没完全写好，后面会继续更的。
